# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gECSjAIVYs5o8LZY6kygHLbKZz31d0e3
"""

!pip install groq

import os
from groq import Groq

# 1. Setup your key
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# 2. Ask the AI a question
completion = client.chat.completions.create(
    model="llama-3.3-70b-versatile", # One of the strongest free models
    messages=[
        {"role": "user", "content": "Explain the role of a Frontend Developer in an AI world."}
    ],
)

# 3. Print the answer
print(completion.choices[0].message.content)

# 1. Read the file you just uploaded
with open('my_data.txt', 'r') as file:
    context_data = file.read()

# 2. Ask a question about that specific data
user_question = "What laptop does Calvin use and what is his favorite project?"

completion = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        # This "system" role tells the AI how to behave
        {"role": "system", "content": f"You are a helpful assistant. Use ONLY this information to answer: {context_data}"},
        {"role": "user", "content": user_question}
    ],
)

print("AI Response based on your file:")
print(completion.choices[0].message.content)

# List your filenames here
my_files = ["work_context.txt", "gaming_context.txt"]

def load_context(file_list):
    combined_text = ""
    for filename in file_list:
        try:
            with open(filename, "r") as f:
                # Add a header so the AI knows which file it is reading
                combined_text += f"\n--- Source: {filename} ---\n"
                combined_text += f.read() + "\n"
        except FileNotFoundError:
            print(f"⚠️ Warning: {filename} not found in Colab folders!")

    return combined_text

# Execute the reading
final_context = load_context(my_files)

print("Files loaded successfully! Preview of context:")
print(final_context[:200] + "...") # Show just the first 200 characters

user_question = "Based on my files, what are the specs of my laptops?"

completion = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "system",
            "content": f"You are a helpful assistant. Answer the question using ONLY the context provided below. Context:\n{final_context}"
        },
        {"role": "user", "content": user_question}
    ],
)

print("\n--- AI ANSWER ---")
print(completion.choices[0].message.content)